import { ThemeConfig } from "../../common/models";

const COLORS = {
  // theme colors
  blueBlack: "#061834",
  darkerBlue: "#091747",
  darkBlue: "#071765",
  royalBlue: "#0b2eac",
  electricBlue: "#1543d8",
  greyBlue: "#889dc5",
  blue: "#477bff",
  lightBlue: "#afcaff",
  lighterBlue: "#c9d5eb",
  primary: "#477bff",
  secondary: "#afcaff",
  tertiary: "#0b2eac",
  accent: "#477bff",
  active: "#afcaff",
  neutral: "#889dc5",
  // bw shades
  // darker: "#0c0c0c",
  // dark: "#2a2a2a",
  // darkerGrey: "#323232",
  // darkGrey: "#505050",
  // grey: "#8f8f8f",
  // lightGrey: "#c8c8c8",
  // lighterGrey: "#ececec",
  // light: "#fbf8f4",
  // lighter: "#fdfdfd",
  black: "#0c0c0c",
  white: "#fdfdfd",
  dark: {
    DEFAULT: "#1c1c1c",
    900: "#0c0c0c",
    800: "#1c1c1c",
    700: "#2a2a2a",
    600: "#323232",
    550: "#3f3f3f",
    500: "#505050",
    400: "#c8c8c8",
    300: "#ececec",
    200: "#fbf8f4",
    100: "#fdfdfd",
  },
  // vivid colors
  green: "#10f3a1",
  orange: "#f8b024",
  red: "#ff4242",
  yellow: "#ffd61e",
  cyan: "#2ee7e7",
  pink: "#ff70ff",
  // sentiment aliases
  info: "#477bff",
  success: "#10f3a1",
  warning: "#f8b024",
  failure: "#ff4242",
  error: "#ff4242",
};

const THEMES: { [name: string]: ThemeConfig } = {
  dark: {
    ...COLORS,
    name: "dark",
    titleFont: "Gilroy",
    bodyFont: "Inter",
    monoFont: "IBM Plex Mono",
    fg0: COLORS.white,
    fg1: COLORS.lighterBlue,
    fg2: COLORS.lightBlue,
    fg3: COLORS.greyBlue,
    bg0: COLORS.blueBlack,
    bg1: COLORS.darkerBlue,
    bg2: COLORS.darkBlue,
    bg3: COLORS.royalBlue,
  },
  light: {
    ...COLORS,
    name: "light",
    titleFont: "Gilroy",
    bodyFont: "Inter",
    monoFont: "IBM Plex Mono",
    fg0: COLORS.black,
    fg1: COLORS.darkerBlue,
    fg2: COLORS.darkBlue,
    fg3: COLORS.greyBlue,
    bg0: COLORS.dark[200],
    bg1: COLORS.dark[300],
    bg2: COLORS.lighterBlue,
    bg3: COLORS.lightBlue,
  },
};

export { COLORS, THEMES };
