[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std=lib/forge-std",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@axelar-network/contracts/=lib/axelar-network/axelar-gmp-sdk-solidity/contracts"
]
